# Generated by Django 5.0 on 2024-01-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
